version: '3'

services:
  node-app:
    build: .
    image: restaurant-management-node
    env_file: '.env'
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mysql:
    image: mysql:8.0
    container_name: node-app-db
    command: --character-set-server=utf8mb4 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
