version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mysql:
    image: mysql:8.0.25
    container_name: node-app-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: hotel_management
      MYSQL_USER: 'hotel_management_user'
      MYSQL_PASSWORD: '123456'
      LANG: C.UTF-8
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
