const routes = {
  ADMIN_AUTH: "/admin/auth",
  DASHBOARD: "/admin",
  BRANCH: "/admin/branches",
  FINANCE: "/admin/finance",
  INVENTORY: "/admin/inventories",
  GOODS: "/admin/goods",
  FACILITIES: "/admin/facilities",
  CUSTOMERS: "/admin/customers",
  STAFF: "/admin/staff",
  MENUS: "/admin/menus",
  SETTINGS: "/admin/settings",
  DISCOUNTS: "/admin/discounts",
  RESERVATIONS: "/admin/reservations",
  KITCHEN_DISPLAY: "/admin/kds",
  ORDERS: "/admin/orders",
  CUSTOMER_HOME: "/",
  CUSTOMER_MENUS: "/menus",
  CUSTOMER_MENU_DETAIL: "/menus/:id",
  CUSTOMER_PROFILE: "/profile/:id",

  CUSTOMER_RESERVATIONS: "/reservations",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CUSTOMER_ORDER: "/orders",
  CUSTOMER_RESERVATION_DETAIL: "/reservations/:id",
  CUSTOMER_ORDER_SUMMARY: "/orders/:id",
};
export default routes;
